version: '3'

services:
  app:
    image: 'volunteers:latest'
    build:
      context: .
    depends_on:
      - postgres
    links:
      - postgres
    ports:
      - "8080:8080"
    network_mode: bridge
    container_name: app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/volunteers
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  postgres:
    image: 'postgres:latest'
    ports:
      - "5432:5432"
    restart: always
    container_name: db
    network_mode: bridge
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=volunteers